/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ms3.training.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the courses service. Represents a row in the &quot;course_courses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ms3.training.services.model.impl.coursesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ms3.training.services.model.impl.coursesImpl}.
 * </p>
 *
 * @author John
 * @see courses
 * @see com.ms3.training.services.model.impl.coursesImpl
 * @see com.ms3.training.services.model.impl.coursesModelImpl
 * @generated
 */
public interface coursesModel extends BaseModel<courses> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a courses model instance should use the {@link courses} interface instead.
	 */

	/**
	 * Returns the primary key of this courses.
	 *
	 * @return the primary key of this courses
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this courses.
	 *
	 * @param primaryKey the primary key of this courses
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the title of this courses.
	 *
	 * @return the title of this courses
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this courses.
	 *
	 * @param title the title of this courses
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this courses.
	 *
	 * @return the description of this courses
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this courses.
	 *
	 * @param description the description of this courses
	 */
	public void setDescription(String description);

	/**
	 * Returns the list price of this courses.
	 *
	 * @return the list price of this courses
	 */
	@AutoEscape
	public String getListPrice();

	/**
	 * Sets the list price of this courses.
	 *
	 * @param listPrice the list price of this courses
	 */
	public void setListPrice(String listPrice);

	/**
	 * Returns the provider of this courses.
	 *
	 * @return the provider of this courses
	 */
	@AutoEscape
	public String getProvider();

	/**
	 * Sets the provider of this courses.
	 *
	 * @param provider the provider of this courses
	 */
	public void setProvider(String provider);

	/**
	 * Returns the course ID of this courses.
	 *
	 * @return the course ID of this courses
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this courses.
	 *
	 * @param courseId the course ID of this courses
	 */
	public void setCourseId(long courseId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(courses courses);

	@Override
	public int hashCode();

	@Override
	public CacheModel<courses> toCacheModel();

	@Override
	public courses toEscapedModel();

	@Override
	public courses toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}