/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ms3.training.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.ms3.training.services.model.course_assignment;
import com.ms3.training.services.service.course_assignmentLocalServiceUtil;

/**
 * The extended model base implementation for the course_assignment service. Represents a row in the &quot;course_course_assignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link course_assignmentImpl}.
 * </p>
 *
 * @author John
 * @see course_assignmentImpl
 * @see com.ms3.training.services.model.course_assignment
 * @generated
 */
public abstract class course_assignmentBaseImpl
	extends course_assignmentModelImpl implements course_assignment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course_assignment model instance should use the {@link course_assignment} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			course_assignmentLocalServiceUtil.addcourse_assignment(this);
		}
		else {
			course_assignmentLocalServiceUtil.updatecourse_assignment(this);
		}
	}
}